train:
  batch_size: 256
  epochs: 10

model:
  hidden_units: [128, 64, 32]
  dropout_rate: 0.5

data:
  train_data_path: 'data/train.csv'
  valid_data_path: 'data/valid.csv'
  test_data_path: 'data/test.csv'
  label_column: label
